class_name ProfileConstants
extends Node

# Resolved through TranslationServer.translate() from the tables below, so no tr("LITERAL")
# scan can see them. Declared here instead; the glob also fails if a key is misspelt.

const COUNTRIES = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cape Verde",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo (Congo-Brazzaville)",
	"Congo (Democratic Republic of the)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czechia",
	"Decentraland",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini (Swaziland)",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (North)",
	"Korea (South)",
	"Kosovo",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar (Burma)",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine State",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syria",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Other"
]

const LANGUAGES = [
	"Afrikaans",
	"Albanian",
	"Amharic",
	"Arabic",
	"Armenian",
	"Azerbaijani",
	"Basque",
	"Belarusian",
	"Bengali",
	"Bosnian",
	"Bulgarian",
	"Catalan",
	"Chinese",
	"Croatian",
	"Czech",
	"Danish",
	"Dutch",
	"English",
	"Estonian",
	"Finnish",
	"French",
	"Galician",
	"Georgian",
	"German",
	"Greek",
	"Gujarati",
	"Hebrew",
	"Hindi",
	"Hungarian",
	"Icelandic",
	"Indonesian",
	"Irish",
	"Italian",
	"Japanese",
	"Javanese",
	"Kannada",
	"Kazakh",
	"Khmer",
	"Korean",
	"Kurdish",
	"Kyrgyz",
	"Lao",
	"Latvian",
	"Lithuanian",
	"Macedonian",
	"Malay",
	"Malayalam",
	"Maltese",
	"Maori",
	"Marathi",
	"Mongolian",
	"Nepali",
	"Norwegian",
	"Pashto",
	"Persian",
	"Polish",
	"Portuguese",
	"Punjabi",
	"Romanian",
	"Russian",
	"Samoan",
	"Serbian",
	"Sindhi",
	"Sinhala",
	"Slovak",
	"Slovenian",
	"Somali",
	"Spanish",
	"Swahili",
	"Swedish",
	"Tagalog",
	"Tajik",
	"Tamil",
	"Telugu",
	"Thai",
	"Tibetan",
	"Tigrinya",
	"Turkish",
	"Turkmen",
	"Ukrainian",
	"Urdu",
	"Uyghur",
	"Uzbek",
	"Vietnamese",
	"Welsh",
	"Xhosa",
	"Yiddish",
	"Yoruba",
	"Zulu",
	"Other"
]

const EMPLOYMENT_STATUS = [
	"Studying", "Working", "Chilling", "Looking for a job", "Home/Family", "Retired", "Other"
]

## Which option table backs each profile field.

static var genders = [
	{"id": "Female", "key": TranslationKey.new("PROFILE_GENDER_FEMALE")},
	{"id": "Male", "key": TranslationKey.new("PROFILE_GENDER_MALE")},
	{"id": "Transgender", "key": TranslationKey.new("PROFILE_GENDER_TRANSGENDER")},
	{"id": "Neutral", "key": TranslationKey.new("PROFILE_GENDER_NEUTRAL")},
	{"id": "Non-Binary", "key": TranslationKey.new("PROFILE_GENDER_NON_BINARY")},
	{"id": "Fluid", "key": TranslationKey.new("PROFILE_GENDER_FLUID")},
	{"id": "Agender", "key": TranslationKey.new("PROFILE_GENDER_AGENDER")},
	{"id": "Pangender", "key": TranslationKey.new("PROFILE_GENDER_PANGENDER")},
	{"id": "Queer", "key": TranslationKey.new("PROFILE_GENDER_QUEER")},
	{"id": "Two-Spirit", "key": TranslationKey.new("PROFILE_GENDER_TWO_SPIRIT")},
	{"id": "Other", "key": TranslationKey.new("PROFILE_GENDER_OTHER")},
]

static var sexual_orientations = [
	{"id": "Heterosexual", "key": TranslationKey.new("PROFILE_ORIENTATION_HETEROSEXUAL")},
	{"id": "Bisexual", "key": TranslationKey.new("PROFILE_ORIENTATION_BISEXUAL")},
	{"id": "Lesbian", "key": TranslationKey.new("PROFILE_ORIENTATION_LESBIAN")},
	{"id": "Gay", "key": TranslationKey.new("PROFILE_ORIENTATION_GAY")},
	{"id": "Asexual", "key": TranslationKey.new("PROFILE_ORIENTATION_ASEXUAL")},
	{"id": "Queer", "key": TranslationKey.new("PROFILE_ORIENTATION_QUEER")},
	{"id": "Polysexual", "key": TranslationKey.new("PROFILE_ORIENTATION_POLYSEXUAL")},
	{"id": "Pansexual", "key": TranslationKey.new("PROFILE_ORIENTATION_PANSEXUAL")},
	{"id": "Other", "key": TranslationKey.new("PROFILE_ORIENTATION_OTHER")},
]

static var pronouns = [
	{"id": "He / Him", "key": TranslationKey.new("PROFILE_PRONOUN_HE_HIM")},
	{"id": "She / Her", "key": TranslationKey.new("PROFILE_PRONOUN_SHE_HER")},
	{"id": "They / Them", "key": TranslationKey.new("PROFILE_PRONOUN_THEY_THEM")},
	{"id": "Ze / Zir", "key": TranslationKey.new("PROFILE_PRONOUN_ZE_ZIR")},
	{"id": "Xe / Xem", "key": TranslationKey.new("PROFILE_PRONOUN_XE_XEM")},
	{"id": "Ze / Hir", "key": TranslationKey.new("PROFILE_PRONOUN_ZE_HIR")},
	{"id": "Per / Per", "key": TranslationKey.new("PROFILE_PRONOUN_PER_PER")},
	{"id": "Other", "key": TranslationKey.new("PROFILE_PRONOUN_OTHER")},
]

static var relationship_status = [
	{"id": "Single", "key": TranslationKey.new("PROFILE_RELATIONSHIP_SINGLE")},
	{
		"id": "In a relationship",
		"key": TranslationKey.new("PROFILE_RELATIONSHIP_IN_A_RELATIONSHIP")
	},
	{"id": "Engaged", "key": TranslationKey.new("PROFILE_RELATIONSHIP_ENGAGED")},
	{"id": "Married", "key": TranslationKey.new("PROFILE_RELATIONSHIP_MARRIED")},
	{"id": "It's complicated", "key": TranslationKey.new("PROFILE_RELATIONSHIP_IT_S_COMPLICATED")},
	{
		"id": "In an open relationship",
		"key": TranslationKey.new("PROFILE_RELATIONSHIP_IN_AN_OPEN_RELATIONSHIP")
	},
	{"id": "Widowed", "key": TranslationKey.new("PROFILE_RELATIONSHIP_WIDOWED")},
	{"id": "Separated", "key": TranslationKey.new("PROFILE_RELATIONSHIP_SEPARATED")},
	{"id": "Divorced", "key": TranslationKey.new("PROFILE_RELATIONSHIP_DIVORCED")},
	{"id": "Other", "key": TranslationKey.new("PROFILE_RELATIONSHIP_OTHER")},
]

static var field_options := {
	"pronouns": pronouns,
	"gender": genders,
	"sexual_orientation": sexual_orientations,
	"relationship": relationship_status,
}


## Display label for a stored option value.
##
## The "id" of each option is a STABLE ID, not copy: profile_editor writes it straight into the
## published profile via set_gender() / set_pronouns() and other clients read it back, so it must
## never be translated. Each option carries its own "key" instead, which is what gets shown.
##
## id and key live in the same entry deliberately — a separate lookup table can drift out of step
## with the array, and the failure is silent (the label falls back to raw English).
##
## Keys are per field because "Other" appears in all four tables and "Queer" in two, and they
## inflect differently by category in ES/PT. Unknown values pass through unchanged, so a value
## written by a newer client still displays rather than vanishing.
static func display_name(field: String, value: String) -> String:
	if value.is_empty():
		return ""
	for option in field_options.get(field, []):
		if option["id"] == value:
			# A TranslationKey instance can resolve itself even from here: tr() is a
			# non-static Object method, so the restriction is on static *functions*, not
			# on instances held by one.
			return option["key"].text()
	return value
