name: Setup Vulkan
description: Install Vulkan drivers and tools for GPU rendering

runs:
  using: composite
  steps:
    - name: Debug GPU and Install Vulkan drivers
      shell: bash
      run: |
        echo "=== GPU Information ==="
        lspci | grep -i vga || echo "No VGA controller found"
        lspci | grep -i nvidia || echo "No NVIDIA GPU found"
        lspci | grep -i amd || echo "No AMD GPU found"

        echo ""
        echo "=== Checking GPU drivers ==="
        nvidia-smi || echo "nvidia-smi not available"

        echo ""
        echo "=== Current Vulkan status ==="
        vulkaninfo --summary || echo "vulkaninfo not available"

        echo ""
        echo "=== Installing Vulkan drivers and tools ==="
        sudo apt-get update
        sudo apt-get install -y \
          mesa-vulkan-drivers \
          vulkan-tools \
          vulkan-validationlayers \
          libvulkan1 \
          libvulkan-dev \
          mesa-utils

        echo ""
        echo "=== Post-install GPU information ==="
        glxinfo | grep -i "opengl version" || echo "glxinfo not available"
        glxinfo | grep -i "opengl renderer" || echo "glxinfo not available"

        echo ""
        echo "=== Vulkan devices available ==="
        vulkaninfo --summary || echo "Still no Vulkan available"

        echo ""
        echo "=== Display and X11 setup ==="
        echo "DISPLAY=$DISPLAY"
        xdpyinfo || echo "xdpyinfo not available (expected before Xvfb starts)"

    - name: Prepare graphics rendering
      shell: bash
      run: |
        sudo apt-get -y install xvfb
        sudo /usr/bin/Xvfb :0 -screen 0 1280x1024x24 &
