name: Install Deps
description: Setup deps for each OS

runs:
  using: composite
  steps:
    # Dependencies section
    # => Linux
    - name: Install alsa and udev
      if: runner.os == 'linux'
      shell: bash
      run: "sudo apt-get update\n# alsa and udev\nsudo apt-get install -y --no-install-recommends \\\n  libasound2-dev libudev-dev\n# ffmpeg deps\nsudo apt install -y --no-install-recommends \\\n  clang curl pkg-config libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev\n# livekit deps\nsudo apt install -y libssl-dev libx11-dev libgl1-mesa-dev libxext-dev        \n  #magic___^_^___line\n"
    # => MacOS
    - name: install ffmpeg deps (macOs)
      if: runner.os == 'macos'
      shell: bash
      run: |
        brew install ffmpeg@6 pkg-config
        echo "PKG_CONFIG_PATH=/opt/homebrew/opt/ffmpeg@6/lib/pkgconfig" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/opt/homebrew/opt/ffmpeg@6/include" >> $GITHUB_ENV
        echo "LDFLAGS=-L/opt/homebrew/opt/ffmpeg@6/lib" >> $GITHUB_ENV

    # => Windows
    - name: set CLANG path for ffmpeg deps (windows)
      if: runner.os == 'windows' && matrix.os != 'self-hosted-windows'
      shell: pwsh
      run: |
        $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
        Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
        Invoke-WebRequest "https://github.com/GyanD/codexffmpeg/releases/download/6.0/ffmpeg-6.0-full_build-shared.7z" -OutFile ffmpeg-release-full-shared.7z
        7z x ffmpeg-release-full-shared.7z
        mkdir ffmpeg
        mv ffmpeg-*/* ffmpeg/
        Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
        Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"