name: Import assets
description: Import assets

inputs:
  cache:
    description: 'Whether to use cache for Godot assets'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    # Step 1: Restore cache
    - name: Restore Godot assets cache
      if: inputs.cache == 'true'
      uses: actions/cache@v3
      with:
        path: godot/.godot
        key: ${{ runner.os }}-godot-assets-cache-4.6.1

    # Step 2: Run the command that generates/uses the assets
    - name: Import assets
      shell: bash
      run: cargo run -- import-assets

    # Step 3: Save cache
    - name: Cache Godot assets
      if: inputs.cache == 'true'
      uses: actions/cache@v3
      with:
        path: godot/.godot
        key: ${{ runner.os }}-godot-assets-cache-4.6.1
