//! Host-only (build-time) quantization codegen for the Pulse protocol.
//! Ported from bevy-explorer `crates/dcl_component/build_quant.rs` @ 3f65c164.
//!
//! Reads the `(decentraland.common.quantized[_power])` field options (`{min, max, bits}` /
//! `{max, pow, bits}`) straight from the FileDescriptorSet emitted by `build.rs` and generates
//! `{field}_dequantized()` / `{field}_quantized(v)` / `{field}_step()` accessors for every
//! `decentraland.pulse` message field that carries one. This keeps the `.proto` the single
//! source of truth for the quantization ABI — the exact constants the C# Pulse server bakes via
//! `protoc-gen-bitwise` — instead of hand-transcribing them on the client side, where a silent
//! drift would decode to wrong positions with no compile error.
//!
//! Not a runtime dependency: the emitted file is plain const arithmetic, `include!`d into the
//! `proto_components::pulse` module.

use std::fmt::Write as _;

use prost_reflect::{DescriptorPool, DynamicMessage, Value};

pub fn generate(descriptor_bytes: &[u8], out_path: &std::path::Path) {
    let pool = DescriptorPool::decode(descriptor_bytes).expect("decode descriptor");
    let quant = pool
        .get_extension_by_name("decentraland.common.quantized")
        .expect("quantized extension missing from descriptor");
    let quant_power = pool
        .get_extension_by_name("decentraland.common.quantized_power")
        .expect("quantized_power extension missing from descriptor");

    let mut out = String::new();
    out.push_str(
        "// @generated by build_quant.rs from the (decentraland.common.quantized[_power]) proto options. DO NOT EDIT.\n\n",
    );
    // Inverse of the server's Quantize.Encode: an encoded integer in [0, 2^bits - 1] maps back
    // onto the float range [min, max].
    out.push_str(
        "#[inline]\n\
         fn dequantize(encoded: u32, min: f32, max: f32, bits: u32) -> f32 {\n    \
         let levels = ((1u32 << bits) - 1) as f32;\n    \
         min + (encoded as f32 / levels) * (max - min)\n\
         }\n\n",
    );
    // Inverse of the server's Quantize.EncodePower: an (bits-1)-bit linear unorm magnitude `u` in
    // the high bits plus a sign in the LSB, reconstructed as `sign * max * u^pow`.
    // Zero (code 0) decodes to exactly 0.
    out.push_str(
        "#[inline]\n\
         fn dequantize_power(encoded: u32, max: f32, pow: f32, bits: u32) -> f32 {\n    \
         let mag_steps = ((1u32 << (bits - 1)) - 1) as f32;\n    \
         let u = (encoded >> 1) as f32 / mag_steps;\n    \
         let magnitude = max * u.powf(pow);\n    \
         if encoded & 1 != 0 { -magnitude } else { magnitude }\n\
         }\n\n",
    );
    // The encode side, needed for the outbound PlayerState. Mirror of the server's Quantize.Encode:
    // clamp to [min, max], scale onto [0, 2^bits - 1], round to the nearest integer.
    out.push_str(
        "#[inline]\n\
         fn quantize(value: f32, min: f32, max: f32, bits: u32) -> u32 {\n    \
         let levels = ((1u32 << bits) - 1) as f32;\n    \
         let t = ((value - min) / (max - min)).clamp(0.0, 1.0);\n    \
         (t * levels).round() as u32\n\
         }\n\n",
    );
    // Mirror of the server's Quantize.EncodePower: `(magnitude << 1) | sign`, magnitude from the
    // inverse power curve `(|value|/max)^(1/pow)`. A zero magnitude never sets the sign bit, so a
    // stopped field canonicalizes to 0 and proto3 omits it.
    out.push_str(
        "#[inline]\n\
         fn quantize_power(value: f32, max: f32, pow: f32, bits: u32) -> u32 {\n    \
         let mag_steps = ((1u32 << (bits - 1)) - 1) as f32;\n    \
         let t = (value.abs() / max).clamp(0.0, 1.0);\n    \
         let magnitude = (t.powf(1.0 / pow) * mag_steps).round() as u32;\n    \
         let sign = if value < 0.0 && magnitude != 0 { 1 } else { 0 };\n    \
         (magnitude << 1) | sign\n\
         }\n\n",
    );

    for msg in pool.all_messages() {
        if msg.package_name() != "decentraland.pulse" {
            continue;
        }

        let mut accessors = String::new();
        for field in msg.fields() {
            let opts = field.options();
            let name = field.name();
            // `optional uint32` (delta fields) decodes to `Option<f32>`; a plain `uint32` (the
            // non-optional PlayerState fields) decodes straight to `f32`.
            let optional = field.supports_presence();

            if opts.has_extension(&quant) {
                let value = opts.get_extension(&quant);
                let q = value
                    .as_message()
                    .expect("quantized option must be a message");
                let min = get_f32(q, "min");
                let max = get_f32(q, "max");
                let bits = get_u32(q, "bits");

                let decode = if optional {
                    format!(
                        "    /// Dequantized `{name}` ({min}..={max}, {bits} bits); `None` when absent.\n    \
                         pub fn {name}_dequantized(&self) -> Option<f32> {{\n        \
                         self.{name}.map(|v| dequantize(v, {min}f32, {max}f32, {bits}))\n    \
                         }}\n"
                    )
                } else {
                    format!(
                        "    /// Dequantized `{name}` ({min}..={max}, {bits} bits).\n    \
                         pub fn {name}_dequantized(&self) -> f32 {{\n        \
                         dequantize(self.{name}, {min}f32, {max}f32, {bits})\n    \
                         }}\n"
                    )
                };

                writeln!(
                    accessors,
                    "{decode}    \
                     /// Quantize a float into `{name}` ({min}..={max}, {bits} bits).\n    \
                     pub fn {name}_quantized(value: f32) -> u32 {{\n        \
                     quantize(value, {min}f32, {max}f32, {bits})\n    \
                     }}\n    \
                     /// Quantization step (granularity) of `{name}`: `(max - min) / (2^bits - 1)`.\n    \
                     pub fn {name}_step() -> f32 {{\n        \
                     ({max}f32 - {min}f32) / ((1u32 << {bits}) - 1) as f32\n    \
                     }}",
                )
                .unwrap();
            } else if opts.has_extension(&quant_power) {
                let value = opts.get_extension(&quant_power);
                let q = value
                    .as_message()
                    .expect("quantized_power option must be a message");
                let max = get_f32(q, "max");
                let pow = get_f32(q, "pow");
                let bits = get_u32(q, "bits");

                let decode = if optional {
                    format!(
                        "    /// Dequantized `{name}` (\u{00b1}{max}, power-law pow {pow}, {bits} bits); `None` when absent.\n    \
                         pub fn {name}_dequantized(&self) -> Option<f32> {{\n        \
                         self.{name}.map(|v| dequantize_power(v, {max}f32, {pow}f32, {bits}))\n    \
                         }}\n"
                    )
                } else {
                    format!(
                        "    /// Dequantized `{name}` (\u{00b1}{max}, power-law pow {pow}, {bits} bits).\n    \
                         pub fn {name}_dequantized(&self) -> f32 {{\n        \
                         dequantize_power(self.{name}, {max}f32, {pow}f32, {bits})\n    \
                         }}\n"
                    )
                };

                writeln!(
                    accessors,
                    "{decode}    \
                     /// Quantize a float into `{name}` (\u{00b1}{max}, power-law pow {pow}, {bits} bits).\n    \
                     pub fn {name}_quantized(value: f32) -> u32 {{\n        \
                     quantize_power(value, {max}f32, {pow}f32, {bits})\n    \
                     }}",
                )
                .unwrap();
            }
        }

        if accessors.is_empty() {
            continue;
        }

        writeln!(out, "impl {} {{\n{accessors}\n}}\n", msg.name()).unwrap();
    }

    std::fs::write(out_path, out).expect("write pulse_quant.rs");
}

fn get_f32(message: &DynamicMessage, field: &str) -> f32 {
    match message.get_field_by_name(field).as_deref() {
        Some(Value::F32(v)) => *v,
        other => panic!("quantized.{field} expected f32, got {other:?}"),
    }
}

fn get_u32(message: &DynamicMessage, field: &str) -> u32 {
    match message.get_field_by_name(field).as_deref() {
        Some(Value::U32(v)) => *v,
        other => panic!("quantized.{field} expected u32, got {other:?}"),
    }
}
