//! Generates a small, gitignored GDScript file that bakes launch parameters into
//! the build, so they apply even when the app can't receive CLI args — plain
//! `cargo run -- build` + manual install, a tapped icon, or a TestFlight build.
//!
//! It mirrors the hand-edited `FORCE_DEEPLINK` constant in `global.gd`, but is
//! overwritten on every `run`/`build` from whatever `--deeplink` / `--log-stream`
//! the developer passed. The app reads `const DEEPLINK` from it at startup (see
//! `global.gd::_generated_deeplink`) and applies it through the existing fake-
//! deeplink path, so any deeplink param (log-stream, rust-log, realm, location,
//! iap, …) is honored.

use std::fs::{create_dir_all, write};
use std::path::Path;

use anyhow::Context;

use crate::consts::GODOT_PROJECT_FOLDER;

/// Path (relative to repo root) of the generated file. Gitignored.
const GENERATED_GD: &str = "src/generated/build_config.gd";

/// Combine an explicit `--deeplink` with a `--log-stream` ws URL into a single
/// deeplink string. Returns empty when neither is provided.
pub fn resolve_deeplink(deeplink: Option<&str>, log_stream_ws: Option<&str>) -> String {
    let mut dl = deeplink.unwrap_or("").trim().to_string();
    if let Some(ws) = log_stream_ws {
        if dl.is_empty() {
            dl = "decentraland://open".to_string();
        }
        let sep = if dl.contains('?') { '&' } else { '?' };
        dl = format!("{dl}{sep}log-stream={ws}");
    }
    dl
}

/// Overwrite `godot/src/generated/build_config.gd` with the given deeplink (empty
/// string = no override). Always writes a valid file so the project keeps parsing.
pub fn write_build_config(deeplink: &str) -> Result<(), anyhow::Error> {
    let dir = Path::new(GODOT_PROJECT_FOLDER).join("src/generated");
    create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;

    let escaped = deeplink.replace('\\', "\\\\").replace('"', "\\\"");
    let contents = format!(
        "# AUTO-GENERATED by `cargo run -- run/build`. DO NOT EDIT.\n\
         # Overwritten on every build with the params you pass (--deeplink / --log-stream).\n\
         # Gitignored. Consumed by global.gd::_generated_deeplink().\n\
         extends RefCounted\n\
         \n\
         const DEEPLINK := \"{escaped}\"\n"
    );

    let path = Path::new(GODOT_PROJECT_FOLDER).join(GENERATED_GD);
    write(&path, contents).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}
