name: Set Prod Flag
description: Set PROD_FLAG environment variable based on the current branch (--prod for main, empty otherwise)

runs:
  using: composite
  steps:
    - name: Set prod flag for main branch
      shell: bash
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "PROD_FLAG=--prod" >> $GITHUB_ENV
          echo "✅ Running on main branch - setting PROD_FLAG=--prod"
        else
          echo "PROD_FLAG=" >> $GITHUB_ENV
          echo "ℹ️  Running on ${{ github.ref }} - PROD_FLAG not set (dev build)"
        fi
